src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable
 */
class Property
{
    const HEAT = [
        0 => 'Electric',
        1 => 'Gaz'
    ];

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->sold = false;
        $this->myOptions = new ArrayCollection();
    }
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */

    private $fileName;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     * @Assert\Image(
     *      mimeTypes="image/jpeg"
     * )
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

/**                                                 
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $area;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(pattern="/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\MyOption", inversedBy="properties")
     */
    private $myOptions;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="float", scale=4, precision=6)
     */
    private $latitude;

    /**
     * @ORM\Column(type="float", scale=4, precision=7)
     */
    private $longitude;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        $slugify = new Slugify();
        return $slugify->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getArea(): ?int
    {
        return $this->area;
    }

    public function setArea(int $area): self
    {
        $this->area = $area;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setString(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|MyOption[]
     */
    public function getMyOptions(): Collection
    {
        return $this->myOptions;
    }

    public function addMyOption(MyOption $myOption): self
    {
        if (!$this->myOptions->contains($myOption)) {
            $this->myOptions[] = $myOption;
            $myOption->addProperty($this);
        }

        return $this;
    }

    public function removeMyOption(MyOption $myOption): self
    {
        if ($this->myOptions->contains($myOption)) {
            $this->myOptions->removeElement($myOption);
            $myOption->removeProperty($this);
        }

        return $this;
    }


    /**
     * Get the value of fileName
     * @return string|null
     */ 
    public function getFileName()
    {
        return $this->fileName;
    }

    /**
     * Set the value of fileName
     *
     * @return  self
     */ 
    public function setFileName($fileName)
    {
        $this->fileName = $fileName;

        return $this;
    }

    /**
     * Get the value of imageFile
     *
     * @return  File
     */ 
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * Set the value of imageFile
     *
     * @param  File  $imageFile
     *
     * @return  self
     */ 
    public function setImageFile(File $imageFile)
    {
        $this->imageFile = $imageFile;
        if($this->imageFile instanceof UploadedFile)
        {
            $this->setUpdatedAt(new \DateTime('now'));
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\MyOption;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('area')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, ['choices' => $this->getChoices()])
            ->add('myOptions', EntityType::class, [
                'class' => MyOption::class,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('imageFile', FileType::class, [
                'required' => false
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('latitude')
            ->add('longitude')
            ->add('sold')
            ->add('rooms')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices(): array
    {
        $choices = Property::HEAT;
        $output = [];
        foreach($choices as $key => $value)
        {
            $output[$value] = $key;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Entity\Property;
use App\Repository\PropertyRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Entity\Contact;
use App\Form\ContactType;
use App\Notification\ContactNotification;

class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */

    private $repository;

    /**
     * @var ObjectManager
     */

    private $entityManager;

    public function __construct(PropertyRepository $repository, ObjectManager $entityManager)
    {
        $this->repository = $repository;
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/property", name = "property")
     * @return Response
     */

    public function index(PaginatorInterface $paginator, Request $request) : Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);

        $form->handleRequest($request);

        $properties = $paginator->paginate(
          $this->repository->findAllVisibleQuery($search),
          $request->query->getInt('page', 1),
          12);
        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties' => $properties,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/bien/{slug}-{id}", requirements={"slug": "[a-z0-9\-]*"}, name="property.show")
     *@param Property
     * @return Response
     */

     public function show(Property $property, string $slug, Request $request, ContactNotification $notification): Response
     {
        $contact = new Contact();

        $contact->setProperty($property);

        $form = $this->createForm(ContactType::class, $contact);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $notification->notify($contact);
            $this->addFlash('success', 'Votre email a bien été envoyé');
            // return $this->redirectToRoute('property.show', [
            //     'id' => $property->getId(),
            //     'slug' => $property->getSlug()
            // ]);
        }
    
        if ($property->getSlug() !== $slug)
        {
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }
        return $this->render('property/show.html.twig', [
            'property' => $property,
            'current_menu' => 'properties',
            'form' => $form->createView()
        ]);
     }
}
?>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Tous nos biens {% endblock %}
{% block body %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            {{ form_start(form) }}
                <div class="row">
                    <div class = "col">
                        {{ form_row(form.minSurface) }}
                    </div>
                    <div class = "col">
                        {{ form_row(form.maxPrice) }}
                    </div>
                    <div class = "col">
                        {{ form_row(form.options) }}
                    </div>
                    <div class = "col">
                        <button class = "btn btn-secondary">Rechercher</button>
                    </div>
                </div>
            {{ form_end(form) }}
        </div>
    </div>
    <div class = "container mt-4">
        <div class = "row">
            {% for property in properties %}
                <div class="col-md-4">
                    {% include 'property/property.html.twig' %}
                </div>
            {% endfor %}
        </div>
        <div class="pagination">
          {{ knp_pagination_render(properties) }}
        </div>
    </div>
{% endblock %}

templates/property/property.html.twig
<div class="card mb-4">
  {% if property.fileName %}
      <img src = "{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" alt = "card-img-top"/>
    {% else %}
    <img src = "{{ '/images/properties/empty.jpg' | imagine_filter('thumb') }}" alt = "card-img-top"/> 
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">Title
        <a href = "{{ path('property.show', {slug: property.slug, id: property.id}) }}">
            {{ property.title}}
        </a>
    </h5>
    <p class="card-text">
        {{ property.area }}m² - {{ property.city }} | {{ property.postalcode }}
    </p>
    <div class = "text-primary">
        {{ property.formattedPrice }}
    </div>
  </div>
</div>

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ property.title }}{% endblock %}

{% block body %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    {% if property.fileName %}
                        <img src = "{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" alt = "card-img-top"/>
                        {% else %}
                        <img src = "{{ '/images/properties/empty.jpg' | imagine_filter('medium') }}" alt = "card-img-top"/> 
                    {% endif %}
                </div>
                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2> {{ property.rooms }} - {{ property.area }}</h2>
                    <div class = "text-primary" style = "font-weight: bold; font-size: 4rem;">
                        {{ property.formattedPrice }}
                    </div>
                    <a  id="contact-button" class="btn btn-primary" href="#" style="
                    {% if form.vars.submitted %}
                        display: none;
                    {% endif %}">Contacter l'agence</a>
                    <div id="contact-form" class="mt-4" style="
                    {% if not form.vars.submitted %}
                            display: none;
                    {% endif %}">
                         {% for message in app.flashes('success') %}
                            <div class="alert alert-success" role="alert">
                                {{ message }}
                            </div>   
                        {% endfor %}
                        {{ form_start(form) }}
                            <div class = "row">
                                <div class = "col">{{ form_row(form.firstName) }}</div>
                                <div class = "col">{{ form_row(form.lastName) }}</div>
                            </div>
                            <div class = "row">
                                <div class = "col">{{ form_row(form.phone) }}</div>
                                <div class = "col">{{ form_row(form.email) }}</div>
                            </div>
                            {{ form_rest(form) }}
                            <div class = "form-group">
                                <button type="submit"  class="btn btn-primary">Envoyer</button>
                            </div>

                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <p>
            {{ property.description | nl2br }}
        </p>

        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
                <table class = "table table-stripped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.area }}</td>
                    </tr>
                    <tr>
                        <td>Pièces </td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Etage</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>Spécificités</h2>
                <ul class = "list-group">
                    {% for option in property.myOptions %}
                        <li class = "list-group-item">{{ option.name }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>


    
{% endblock %}